In [12]:
import numpy as np
import matplotlib.pyplot as plt


# !wget https://www.dropbox.com/s/eh1kps73fp88m67/faces.dat

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:

from sympy import *

In [3]:
M = Matrix([[0.9,0,0,0.1],[0,0.8,0.1,0.1],[0,0.1,0.8,0.1],[0.1,0.1,0.1,0.7]])
 
P,D = M.diagonalize()
print(P)
print(D)

Matrix([[7.48461010574286e-64, 0.816496580927726, -0.500000000000000, -0.288675134594813], [0.707106781186548, -0.408248290463863, -0.500000000000000, -0.288675134594813], [-0.707106781186548, -0.408248290463863, -0.500000000000000, -0.288675134594813], [-2.92041828790221e-64, 7.55411086394732e-17, -0.500000000000000, 0.866025403784439]])
Matrix([[0.700000000000000, 0, 0, 0], [0, 0.900000000000000, 0, 0], [0, 0, 1.00000000000000, 0], [0, 0, 0, 0.600000000000000]])


In [4]:
P*Matrix([[0,0,0,0],[0,0,0,0],[0,0,1,0],[0,0,0,0]])*(P**-1)*Matrix([0.25,0.25,0.25,0.25])

Matrix([
[0.25],
[0.25],
[0.25],
[0.25]])

In [5]:
M*Matrix([0.25,0.25,0.25,0.25])

Matrix([
[0.25],
[0.25],
[0.25],
[0.25]])

In [12]:
P*D*(P**(-1))

Matrix([
[                  0.9, -2.08166817117217e-17, -2.08166817117217e-17,                0.1],
[-6.93889390390723e-18,                   0.8,                   0.1,                0.1],
[-6.93889390390723e-18,                   0.1,                   0.8, 0.0999999999999999],
[                  0.1,                   0.1,                   0.1,                0.7]])

In [13]:
faces=np.genfromtxt('faces.dat')

In [14]:
#perfom PCA for eigenfaces, show the reconstruction of faces project on 10,100,200 principle components
from sklearn.decomposition import PCA
pca=PCA(n_components=10)
faces_10=pca.fit_transform(faces)
print(faces_10.shape)
faces_10

(400, 10)


array([[-1556.69211597,  -170.2879445 ,  -346.06554321, ...,
         -711.04585249,   -90.50223873,    58.91736763],
       [ -260.36635982, -1620.75455486,   445.95784034, ...,
         -508.52009313,  -259.59452326,   499.15022021],
       [-1280.89374027,  -373.28781854,    54.68051574, ...,
         -771.82666211,  -378.84971307,   145.14236816],
       ...,
       [  493.86529277,  -365.32668241,   834.59321413, ...,
          409.62694058,  -675.85226968,  -337.97116519],
       [-1249.98706108,  1959.4161341 ,  -162.38324898, ...,
          307.5190246 ,  -263.6246285 ,  -272.95726294],
       [ -278.42167374,   589.27766304,   287.85807587, ...,
         -268.37989637,    56.4168801 ,  -389.83570737]])

In [15]:
pca=PCA(n_components=100)
faces_100=pca.fit_transform(faces)
print(faces_100.shape)
faces_100

(400, 100)


array([[-1556.69211597,  -170.2879445 ,  -346.06554292, ...,
          133.09397695,   -75.0218888 ,    35.47189526],
       [ -260.36635982, -1620.75455487,   445.95784021, ...,
          -50.89643738,   -13.98840432,   106.71135672],
       [-1280.89374027,  -373.28781855,    54.68051645, ...,
           49.79686411,    29.07825724,   -42.06235445],
       ...,
       [  493.86529277,  -365.32668241,   834.59321427, ...,
          -46.29957541,   -19.50506738,   -23.42764332],
       [-1249.98706108,  1959.4161341 ,  -162.38324892, ...,
           66.39257201,   -22.47889581,    27.78975282],
       [ -278.42167374,   589.27766304,   287.85807548, ...,
          -14.04075517,   -30.64555471,    17.72692018]])

In [16]:
pca=PCA(n_components=200)
faces_200=pca.fit_transform(faces)
print(faces_200.shape)
faces_200

(400, 200)


array([[-1.55669212e+03, -1.70287944e+02, -3.46065543e+02, ...,
         1.06905923e+01,  1.76520549e+01,  2.72222897e+01],
       [-2.60366360e+02, -1.62075455e+03,  4.45957840e+02, ...,
        -2.81630479e+01, -1.19517820e+01, -3.38203030e+01],
       [-1.28089374e+03, -3.73287819e+02,  5.46805165e+01, ...,
         1.27933794e+00, -2.13720182e+01, -5.59563609e+01],
       ...,
       [ 4.93865293e+02, -3.65326682e+02,  8.34593214e+02, ...,
         1.02049694e+01, -3.65778602e+01, -4.84924348e+00],
       [-1.24998706e+03,  1.95941613e+03, -1.62383249e+02, ...,
         6.24557185e+00, -8.00834324e+00,  9.98794243e+00],
       [-2.78421674e+02,  5.89277663e+02,  2.87858075e+02, ...,
        -5.07746373e+00,  3.28963532e+01, -3.06721770e+01]])